template-file-path: root-stack.yaml
parameters:
  GithubOrg: wodoame
  GithubAppRepo: BEM14-photo-uploader-app
  Environment: production
  TemplatesBucketName: bem14-photo-uploader-stacks
tags:
  Project: bem14-photo-uploader
  ManagedBy: CloudFormation
  Environment: production
